### ISSUE TITLE
Make react a peer dependency

### ISSUE THREAD

**Issue by pioul** [oyvindhermansen/react-images-loaded#10]
This will ensure all projects using this package will not have two different versions of React running

**Comment by oyvindhermansen** [comment]
Hey @pioul . Thanks for reporting this. Feel free to make a PR with the fix, or let me know if you want me to do it. :)

**Comment by pioul** [comment]
Hey, the app I'm working with is still using React 15 so I forked 1.0.1 and
made the change there – master being on React 16, feel free to make that
one-line change yourself for master :)

Thanks for that helpful wrapper component!

**Comment by oyvindhermansen** [comment]
Thanks :) Hope you like it!
