### ISSUE TITLE
background option

### ISSUE THREAD

**Issue by gl03** [oyvindhermansen/react-images-loaded#13]
Hi!

This works nicely so far, but I'm unsure how to make the background option work.

'true or child selector' -> should i use the query string of my background-image div, (which will always be a child component of <ImagesLoaded>) or should i just use _true_ if the div is a direct descendant of <ImagesLoaded>?

If it's the latter, i'm unsure about the syntax - should it be: background={true} ?

Thank you!

**Comment by oyvindhermansen** [comment]
Hi! Thanks for your question! :) 

I can see why this can be confusing. 

The best way I can explain this is by quoting the official docs of Images loaded:

> Set to a selector string like `{ background: '.item' }` to detect when the background images of child elements have loaded.

and

> Set `{ background: true }` to detect when the element's background image has loaded.

In your case, i would think that `background={true}` will do.

I hope that answers your question in a way!

Let me know if this is still very unclear. I might be able to set up an example in a few days.
